### ISSUE TITLE
releaseScript sign_target_files_apks.py fails

### ISSUE THREAD

**Issue by Cornu** [danielfullmer/robotnix#37]
After manually fixing #36 the release script fails with:

```
$ ./release.sh ./keys/sargo/
Signing target files
Traceback (most recent call last):
  File "/nix/store/5pn49s6g3qmam9g48x7j706m681mnisl-ota-tools/releasetools/sign_target_files_apks.py", line 1231, in <module>
    main(sys.argv[1:])
  File "/nix/store/5pn49s6g3qmam9g48x7j706m681mnisl-ota-tools/releasetools/sign_target_files_apks.py", line 1186, in main
    allowZip64=True)
  File "/nix/store/106ax16ascs6xcn4af498gp5axsxqwzk-python-2.7.17/lib/python2.7/zipfile.py", line 779, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 30] Read-only file system: 'sargo-signed_target_files-2020.09.13.04.zip'
```

**Comment by danielfullmer** [comment]
Should be fixed by 883113139ba8212d5a5017412c1e8c502b7ec8eb
