### ISSUE TITLE
Vanilla flavor signing fails with release script

### ISSUE THREAD

**Issue by Cornu** [danielfullmer/robotnix#38]
Trying to sign a vanilla build with the releaseScript fails with:

```
    ...
    signing: StorageManager.apk                                (/home/cornu/robotnix/keys_copy/releasekey)
    signing: SystemUI.apk                                      (/home/cornu/robotnix/keys_copy/platform)
    signing: WallpaperCropper.apk                              (/home/cornu/robotnix/keys_copy/platform)
Rewriting ROOT/default.prop:
NOT signing: com.android.apex.cts.shim.apex
        (skipped due to special cert string)
    signing: com.android.conscrypt.apex                        container (external/conscrypt/apex/com.android.conscrypt)
           : com.android.conscrypt.apex                        payload   (external/conscrypt/apex/com.android.conscrypt.pem)
Traceback (most recent call last):
  File "/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/releasetools/sign_target_files_apks.py", line 1230, in <module>
    main(sys.argv[1:])
  File "/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/releasetools/sign_target_files_apks.py", line 1211, in main
    compressed_extension)
  File "/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/releasetools/sign_target_files_apks.py", line 456, in ProcessTargetFiles
    OPTIONS.avb_extra_args.get('apex'))
  File "/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/releasetools/apex_utils.py", line 189, in SignApex
    signing_args)
  File "/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/releasetools/apex_utils.py", line 60, in SignApexPayload
    common.RunAndCheckOutput(cmd)
  File "/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/releasetools/common.py", line 252, in RunAndCheckOutput
    args, proc.returncode, output))
apex_utils.ApexSigningError: Failed to sign APEX payload /tmp/apex-payload-NzhwS0/apex_payload.img with external/conscrypt/apex/com.android.conscrypt.pem:
Failed to run command '['avbtool', 'add_hashtree_footer', '--do_not_generate_fec', '--algorithm', 'SHA256_RSA4096', '--key', 'external/conscrypt/apex/com.android.conscrypt.pem', '--prop', 'apex.key:com.android.conscrypt', '--image', u'/tmp/apex-payload-NzhwS0/apex_payload.img', '--salt', '3fb5afc28008dd6fb96233dba479bd19ff50027064f0278d80f0a77b142c8766']' (exit code 1):
/nix/store/mlmf66xfpa4ha56yb54xya21ay5xy9wf-ota-tools/bin/.avbtool: Error getting public key: Can't open external/conscrypt/apex/com.android.conscrypt.pem for reading, No such file or directory
140632981828864:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('external/conscrypt/apex/com.android.conscrypt.pem','r')
140632981828864:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load Public Key
```

The same config with graphenos flavor works and signs the build.

**Comment by danielfullmer** [comment]
So the cause of this one is that Android 10 introduced a new set of keys, called "APEX" keys. GrapheneOS disables the ability to update APEX packages, so they have no need to generate keys for them.  The `vanilla` flavor in robotnix does use APEX keys, so the `generateKeysScript` created for a `vanilla` build will actually create a bunch more keys for the APEX packages.
