### ISSUE TITLE
Updater app not working with vanilla flavor

### ISSUE THREAD

**Issue by danielfullmer** [danielfullmer/robotnix#93]
I've found the updater app currently doesn't work with the vanilla flavor in robotnix. It currently fails with:

```
03-02 11:06:35.838  5876 20201 D Service : fetch incremental sunfish-incremental-2021.02.02.17-2021.03.02.08.zip
03-02 11:06:36.042  5876 20201 D Service : incremental not found, fetch full update sunfish-ota_update-2021.03.02.08.zip
03-02 11:06:36.861  5876  5876 W IntentService[S: type=1400 audit(0.0:3418): avc: denied { search } for name="ota_package" dev="dm-9" ino=93 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:ota_package_file:s0 tclass=dir permissive=0 app=app.seamlessupdate.client
03-02 11:06:36.864  5876 20201 E Service : failed to download and install update
03-02 11:06:36.864  5876 20201 E Service : java.nio.file.AccessDeniedException: /data/ota_package/update.zip
03-02 11:06:36.864  5876 20201 E Service : 	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
03-02 11:06:36.864  5876 20201 E Service : 	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
03-02 11:06:36.864  5876 20201 E Service : 	at java.nio.file.Files.deleteIfExists(Files.java:1165)
03-02 11:06:36.864  5876 20201 E Service : 	at app.seamlessupdate.client.Service.onHandleIntent(Service.java:284)
03-02 11:06:36.864  5876 20201 E Service : 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
03-02 11:06:36.864  5876 20201 E Service : 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-02 11:06:36.864  5876 20201 E Service : 	at android.os.Looper.loop(Looper.java:223)
03-02 11:06:36.864  5876 20201 E Service : 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

We likely need to include the relevant selinux policies for `updater_app` from https://github.com/GrapheneOS/platform_system_sepolicy

**Comment by danielfullmer** [comment]
Fixed by 7da8c8c5fd64aaab06d132397ada3ee23761ce29
